name: ğŸ“¦ 00_build-rootfs-lite
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: â¬ ä¸‹è½½ ImageBuilder
        run: |
          curl -L -o imagebuilder.tar.zst https://github.com/Kwonelee/fenliu/releases/download/rootfs/istoreos-imagebuilder-24.10.2-armsr-armv8.Linux-x86_64.tar.zst
          tar --use-compress-program=unzstd -xvf imagebuilder.tar.zst
          mv istoreos-imagebuilder-* imagebuilder

      - name: âš™ï¸ å®‰è£…ä¾èµ–
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zstd curl unzip tree

      - name: ğŸ§± æ„å»ºiStoreOS-rootfs
        run: |
          #cd imagebuilder
          #echo "å¯ç”¨rootfs.tar.gzé…ç½®"
          #sed -i 's/# CONFIG_TARGET_ROOTFS_TARGZ is not set/CONFIG_TARGET_ROOTFS_TARGZ=y/' .config
          cd imagebuilder
          make image PROFILE=generic PACKAGES="luci dnsmasq-full -dnsmasq luci-i18n-firewall-zh-cn luci-app-filetransfer luci-i18n-base-zh-cn luci-i18n-ttyd-zh-cn luci-i18n-package-manager-zh-cn luci-i18n-argon-zh-cn luci-theme-argon luci-i18n-argon-config-zh-cn luci-i18n-quickstart-zh-cn luci-i18n-dockerman-zh-cn -libustream-mbedtls" FILES="files"

      - name: ğŸš€ ä¸Šä¼ åˆ° Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: iStoreOS-24.10.2-arm64-rootfs-lite
          files: |
            imagebuilder/bin/targets/armsr/armv8/*generic-rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
