name: ğŸ“¦ 01_build-rootfs-lite
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: âš™ï¸ å®‰è£…ä¾èµ–
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zstd curl unzip tree

    - name: â¬ ä¸‹è½½ ImageBuilder
      run: |
        curl -L -o imagebuilder.tar.zst https://github.com/Kwonelee/fenliu/releases/download/rootfs/istoreos-imagebuilder-24.10.2-armsr-armv8.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xvf imagebuilder.tar.zst
        mv istoreos-imagebuilder-* imagebuilder

    - name: â¬ å¤åˆ¶å¹¶è®¾ç½®å¿…å¤‡æ–‡ä»¶
      run: |
        cp arm64/Makefile imagebuilder/
        cp files/etc/packages/*.ipk imagebuilder/packages/
        mkdir -p imagebuilder/files/etc/uci-defaults
        cp files/etc/uci-defaults/99-custom.sh imagebuilder/files/etc/uci-defaults/
        mkdir -p imagebuilder/files/etc/banner1
        cp files/etc/banner imagebuilder/files/etc/banner1/
        cd imagebuilder
        echo "å¯ç”¨rootfs.tar.gzé…ç½®å¹¶åœç”¨éå¿…è¦é…ç½®"
        sed -i 's/# CONFIG_TARGET_ROOTFS_TARGZ is not set/CONFIG_TARGET_ROOTFS_TARGZ=y/' .config
        sed -i "s|CONFIG_TARGET_ROOTFS_SQUASHFS=.*|# CONFIG_TARGET_ROOTFS_SQUASHFS is not set|g" .config
        sed -i "s|CONFIG_TARGET_IMAGES_GZIP=.*|# CONFIG_TARGET_IMAGES_GZIP is not set|g" .config

    - name: ğŸ§± æ„å»ºiStoreOS-rootfs
      run: |
        cd imagebuilder
        make image PROFILE=generic PACKAGES="\
           acpid attr base-files bash bc blkid block-mount blockd bsdtar btrfs-progs busybox bzip2 \
           cgi-io chattr comgt comgt-ncm containerd coremark coreutils coreutils-base64 coreutils-nohup \
           coreutils-truncate curl docker docker-compose dockerd dosfstools dumpe2fs e2freefrag e2fsprogs \
           exfat-mkfs f2fs-tools f2fsck fdisk gawk getopt git gzip hostapd-common iconv iw iwinfo jq \
           jshn kmod-brcmfmac kmod-brcmutil kmod-cfg80211 kmod-mac80211 libjson-script liblucihttp \
           liblucihttp-lua losetup lsattr lsblk lscpu mkf2fs mount-utils openssl-util parted \
           perl-http-date perlbase-file perlbase-getopt perlbase-time -perlbase-unicode perlbase-utf8 \
           pigz ppp ppp-mod-pppoe pv rename resize2fs runc tar tini ttyd tune2fs \
           uclient-fetch uhttpd uhttpd-mod-ubus unzip uqmi usb-modeswitch uuidgen wget-ssl whereis \
           which wpad-basic wwan xfs-fsck xfs-mkfs xz xz-utils ziptool zoneinfo-asia zoneinfo-core zstd \
           \
           luci luci-base luci-compat luci-i18n-base-zh-cn luci-lib-base luci-lib-docker \
           luci-lib-ip luci-lib-ipkg luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-network \
           luci-mod-status luci-mod-system luci-proto-3g luci-proto-ipip luci-proto-ipv6 \
           luci-proto-ncm luci-proto-openconnect luci-proto-ppp luci-proto-qmi luci-proto-relay \
           \
           -dnsmasq dnsmasq-full luci-i18n-firewall-zh-cn luci-i18n-ttyd-zh-cn luci-i18n-package-manager-zh-cn \
           luci-theme-argon luci-i18n-argon-zh-cn luci-app-argon-config luci-i18n-argon-config-zh-cn \
           \
           luci-i18n-quickstart-zh-cn luci-i18n-dockerman-zh-cn \
           luci-app-amlogic luci-i18n-amlogic-zh-cn \
           \
           -libustream-mbedtls" FILES="files"

    - name: ğŸš€ ä¸Šä¼ åˆ° Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        tag_name: iStoreOS-rootfs-lite
        files: |
          imagebuilder/bin/targets/armsr/armv8/*generic-rootfs.tar.gz
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
