name: build-1-istore
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_board:
        description: "Select device board"
        required: false
        default: "station-m2"
        type: choice
        options:
          - station-m2

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug workspace contents
        run: ls -R

      - name: Download prebuilt rootfs.tar.gz
        run: |
          echo "ðŸ“¦ æ­£åœ¨ä¸‹è½½é¢„æž„å»º rootfs"
          mkdir -p bin/targets/armsr/armv8
          curl -L -o bin/targets/armsr/armv8/openwrt-armvirt-64-default-rootfs.tar.gz \
            https://github.com/Kwonelee/AutoBuildImmortalWrt/releases/download/istoreos-rootfs/istoreos-armsr-armv8-generic-rootfs.tar.gz

      - name: æŸ¥æ‰¾rootfs.tar.gzæ‰€åœ¨è·¯å¾„
        id: find_rootfs
        run: |
          ROOTFS_FILE=$(find bin/targets/armsr/armv8/ -type f -name "*rootfs.tar.gz" | head -n1)
          echo "âœ… Found: $ROOTFS_FILE"
          if [ ! -f "$ROOTFS_FILE" ]; then
            echo "âŒ æ‰¾ä¸åˆ° rootfs.tar.gz æ–‡ä»¶"
            exit 1
          fi
          echo "file=$ROOTFS_FILE" >> $GITHUB_OUTPUT

      - name: Package openwrt
        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: ${{ steps.find_rootfs.outputs.file }}
          openwrt_board: ${{ inputs.openwrt_board }}
          openwrt_kernel: 5.15.y_6.1.y
          auto_kernel: true
          kernel_repo: ophub/kernel
          kernel_usage: stable
          builder_name: kwonelee

      - name: Rename .img.gz file
        id: rename
        run: |
          FILE=$(ls ${{ env.PACKAGED_OUTPUTPATH }}/*.img.gz | head -n1)
          echo "Image file is: $FILE"
          FILENAME=$(basename "$FILE")
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          KERNEL_VERSION=$(echo "$FILENAME" | grep -oP 'k\d+\.\d+\.\d+')
          mv "$FILE" "${{ env.PACKAGED_OUTPUTPATH }}/istoreos-24.10.2-${{ inputs.openwrt_board }}-$KERNEL_VERSION.img.gz"


      - name: Upload firmware to GitHub Releases
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: istoreos
          name: istoreos for arm_board
          body_path: 
          files: |
            ${{ env.PACKAGED_OUTPUTPATH }}/*.img.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
